// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWHkL2JljNmQg-oUhHK_VpoEDL3TIkyzI',
    appId: '1:87781718160:web:e6ea72703ad3e9e922c015',
    messagingSenderId: '87781718160',
    projectId: 'pulse-market',
    authDomain: 'pulse-market.firebaseapp.com',
    storageBucket: 'pulse-market.firebasestorage.app',
    measurementId: 'G-YTPR36530S',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB19s79BPfZcGFoWCCWfBmGw2SY3mNYNcA',
    appId: '1:87781718160:android:fabc910f4c9bd5a522c015',
    messagingSenderId: '87781718160',
    projectId: 'pulse-market',
    storageBucket: 'pulse-market.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEhbfvchIvUf3Np6amQwQ8SmD5slPHazQ',
    appId: '1:87781718160:ios:c17ff7ae25b2e9cb22c015',
    messagingSenderId: '87781718160',
    projectId: 'pulse-market',
    storageBucket: 'pulse-market.firebasestorage.app',
    iosBundleId: 'com.example.pulsemarket',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEhbfvchIvUf3Np6amQwQ8SmD5slPHazQ',
    appId: '1:87781718160:ios:c17ff7ae25b2e9cb22c015',
    messagingSenderId: '87781718160',
    projectId: 'pulse-market',
    storageBucket: 'pulse-market.firebasestorage.app',
    iosBundleId: 'com.example.pulsemarket',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWHkL2JljNmQg-oUhHK_VpoEDL3TIkyzI',
    appId: '1:87781718160:web:c986ec1b264e014022c015',
    messagingSenderId: '87781718160',
    projectId: 'pulse-market',
    authDomain: 'pulse-market.firebaseapp.com',
    storageBucket: 'pulse-market.firebasestorage.app',
    measurementId: 'G-4Q197Y94L2',
  );
}
